# Generated by Django 5.1.1 on 2024-09-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia2eccApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[(1, 'Cão'), (2, 'Gato')], max_length=4),
        ),
        migrations.DeleteModel(
            name='Senha',
        ),
    ]
